# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qtui.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGridLayout, QGroupBox,
    QHBoxLayout, QLineEdit, QListView, QMainWindow,
    QMenuBar, QPushButton, QRadioButton, QSizePolicy,
    QStatusBar, QWidget)
import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1000, 800))
        MainWindow.setMaximumSize(QSize(1000, 800))
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(760, 720, 239, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ChoiceButtonMain = QPushButton(self.horizontalLayoutWidget)
        self.ChoiceButtonMain.setObjectName(u"ChoiceButtonMain")
        self.ChoiceButtonMain.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.ChoiceButtonMain.sizePolicy().hasHeightForWidth())
        self.ChoiceButtonMain.setSizePolicy(sizePolicy1)

        self.horizontalLayout.addWidget(self.ChoiceButtonMain)

        self.SaveButtonMain = QPushButton(self.horizontalLayoutWidget)
        self.SaveButtonMain.setObjectName(u"SaveButtonMain")
        self.SaveButtonMain.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.SaveButtonMain.sizePolicy().hasHeightForWidth())
        self.SaveButtonMain.setSizePolicy(sizePolicy1)

        self.horizontalLayout.addWidget(self.SaveButtonMain)

        self.StartButtonMain = QPushButton(self.horizontalLayoutWidget)
        self.StartButtonMain.setObjectName(u"StartButtonMain")
        self.StartButtonMain.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.StartButtonMain.sizePolicy().hasHeightForWidth())
        self.StartButtonMain.setSizePolicy(sizePolicy1)
        self.StartButtonMain.setAcceptDrops(False)
        self.StartButtonMain.setFlat(False)

        self.horizontalLayout.addWidget(self.StartButtonMain)

        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(20, 30, 291, 151))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.checkBoxguild = QCheckBox(self.gridLayoutWidget)
        self.checkBoxguild.setObjectName(u"checkBoxguild")
        self.checkBoxguild.setStyleSheet(u"color: rgb(255, 255, 0);\n"
"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxguild.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxguild, 0, 0, 1, 1)

        self.checkBoxcompany = QCheckBox(self.gridLayoutWidget)
        self.checkBoxcompany.setObjectName(u"checkBoxcompany")
        self.checkBoxcompany.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxcompany.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxcompany, 1, 0, 1, 1)

        self.checkBoxfire = QCheckBox(self.gridLayoutWidget)
        self.checkBoxfire.setObjectName(u"checkBoxfire")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.checkBoxfire.sizePolicy().hasHeightForWidth())
        self.checkBoxfire.setSizePolicy(sizePolicy2)
        self.checkBoxfire.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxfire.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxfire, 0, 1, 1, 1)

        self.checkBoxemploy = QCheckBox(self.gridLayoutWidget)
        self.checkBoxemploy.setObjectName(u"checkBoxemploy")
        self.checkBoxemploy.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")

        self.gridLayout.addWidget(self.checkBoxemploy, 1, 1, 1, 1)

        self.checkBoxshop = QCheckBox(self.gridLayoutWidget)
        self.checkBoxshop.setObjectName(u"checkBoxshop")
        self.checkBoxshop.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxshop.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxshop, 2, 0, 1, 1)

        self.checkBoxanyingdiantang = QCheckBox(self.gridLayoutWidget)
        self.checkBoxanyingdiantang.setObjectName(u"checkBoxanyingdiantang")
        self.checkBoxanyingdiantang.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxanyingdiantang.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxanyingdiantang, 2, 1, 1, 1)

        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QRect(180, 200, 129, 151))
        self.groupBox_2.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.radioButton_4 = QRadioButton(self.groupBox_2)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(10, 30, 95, 20))
        self.radioButton_5 = QRadioButton(self.groupBox_2)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(10, 65, 95, 20))
        self.radioButton_6 = QRadioButton(self.groupBox_2)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setGeometry(QRect(10, 100, 95, 20))
        self.groupBoxshengkai = QGroupBox(self.centralwidget)
        self.groupBoxshengkai.setObjectName(u"groupBoxshengkai")
        self.groupBoxshengkai.setEnabled(True)
        self.groupBoxshengkai.setGeometry(QRect(20, 200, 129, 149))
        self.groupBoxshengkai.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.radioButtonshengkai1 = QRadioButton(self.groupBoxshengkai)
        self.radioButtonshengkai1.setObjectName(u"radioButtonshengkai1")
        self.radioButtonshengkai1.setGeometry(QRect(10, 30, 95, 20))
        self.radioButtonshengkai1.setChecked(True)
        self.radioButtonshengkai2 = QRadioButton(self.groupBoxshengkai)
        self.radioButtonshengkai2.setObjectName(u"radioButtonshengkai2")
        self.radioButtonshengkai2.setGeometry(QRect(10, 65, 95, 20))
        self.radioButtonshengkai3 = QRadioButton(self.groupBoxshengkai)
        self.radioButtonshengkai3.setObjectName(u"radioButtonshengkai3")
        self.radioButtonshengkai3.setGeometry(QRect(10, 100, 95, 20))
        self.groupBoxmonizhan = QGroupBox(self.centralwidget)
        self.groupBoxmonizhan.setObjectName(u"groupBoxmonizhan")
        self.groupBoxmonizhan.setGeometry(QRect(30, 400, 291, 91))
        self.groupBoxmonizhan.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxmonizhangongji = QCheckBox(self.groupBoxmonizhan)
        self.checkBoxmonizhangongji.setObjectName(u"checkBoxmonizhangongji")
        self.checkBoxmonizhangongji.setGeometry(QRect(0, 30, 80, 30))
        self.checkBoxmonizhangongji.setChecked(True)
        self.checkBoxmonizhanfangyu = QCheckBox(self.groupBoxmonizhan)
        self.checkBoxmonizhanfangyu.setObjectName(u"checkBoxmonizhanfangyu")
        self.checkBoxmonizhanfangyu.setGeometry(QRect(100, 30, 80, 30))
        self.checkBoxmonizhanfangyu.setChecked(True)
        self.checkBoxmonizhanfangkong = QCheckBox(self.groupBoxmonizhan)
        self.checkBoxmonizhanfangkong.setObjectName(u"checkBoxmonizhanfangkong")
        self.checkBoxmonizhanfangkong.setGeometry(QRect(200, 30, 80, 30))
        self.checkBoxmonizhanfangkong.setChecked(True)
        self.groupBoxbugeizuozhan = QGroupBox(self.centralwidget)
        self.groupBoxbugeizuozhan.setObjectName(u"groupBoxbugeizuozhan")
        self.groupBoxbugeizuozhan.setGeometry(QRect(30, 510, 291, 91))
        self.groupBoxbugeizuozhan.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxbugeizuozhan15 = QCheckBox(self.groupBoxbugeizuozhan)
        self.checkBoxbugeizuozhan15.setObjectName(u"checkBoxbugeizuozhan15")
        self.checkBoxbugeizuozhan15.setGeometry(QRect(0, 30, 80, 30))
        self.checkBoxbugeizuozhan16 = QCheckBox(self.groupBoxbugeizuozhan)
        self.checkBoxbugeizuozhan16.setObjectName(u"checkBoxbugeizuozhan16")
        self.checkBoxbugeizuozhan16.setGeometry(QRect(100, 30, 80, 30))
        self.checkBoxbugeizuozhan16.setChecked(True)
        self.checkBoxbugeizuozhan17 = QCheckBox(self.groupBoxbugeizuozhan)
        self.checkBoxbugeizuozhan17.setObjectName(u"checkBoxbugeizuozhan17")
        self.checkBoxbugeizuozhan17.setGeometry(QRect(200, 30, 80, 30))
        self.checkBoxbugeizuozhan17.setChecked(True)
        self.groupBoxcollect = QGroupBox(self.centralwidget)
        self.groupBoxcollect.setObjectName(u"groupBoxcollect")
        self.groupBoxcollect.setGeometry(QRect(30, 620, 291, 131))
        self.groupBoxcollect.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxcollect1 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect1.setObjectName(u"checkBoxcollect1")
        self.checkBoxcollect1.setGeometry(QRect(0, 30, 80, 30))
        self.checkBoxcollect2 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect2.setObjectName(u"checkBoxcollect2")
        self.checkBoxcollect2.setGeometry(QRect(100, 30, 80, 30))
        self.checkBoxcollect2.setChecked(True)
        self.checkBoxcollect3 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect3.setObjectName(u"checkBoxcollect3")
        self.checkBoxcollect3.setGeometry(QRect(200, 30, 80, 30))
        self.checkBoxcollect3.setChecked(True)
        self.checkBoxcollect4 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect4.setObjectName(u"checkBoxcollect4")
        self.checkBoxcollect4.setGeometry(QRect(0, 70, 80, 30))
        self.checkBoxcollect5 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect5.setObjectName(u"checkBoxcollect5")
        self.checkBoxcollect5.setGeometry(QRect(100, 70, 80, 30))
        self.checkBoxcollect6 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect6.setObjectName(u"checkBoxcollect6")
        self.checkBoxcollect6.setGeometry(QRect(200, 70, 80, 30))
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(30, 360, 80, 19))
        self.checkBox.setStyleSheet(u"color: rgb(255, 255, 0);font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.listView = QListView(self.centralwidget)
        self.listView.setObjectName(u"listView")
        self.listView.setEnabled(True)
        self.listView.setGeometry(QRect(0, 0, 1000, 800))
        self.listView.setStyleSheet(u"border-image: url(:/104950937_p0_master1200.jpg);")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QRect(640, 730, 113, 21))
        MainWindow.setCentralWidget(self.centralwidget)
        self.listView.raise_()
        self.horizontalLayoutWidget.raise_()
        self.gridLayoutWidget.raise_()
        self.groupBox_2.raise_()
        self.groupBoxshengkai.raise_()
        self.groupBoxmonizhan.raise_()
        self.groupBoxbugeizuozhan.raise_()
        self.groupBoxcollect.raise_()
        self.checkBox.raise_()
        self.lineEdit.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.StartButtonMain.clicked.connect(MainWindow.close)
        self.SaveButtonMain.clicked.connect(MainWindow.SaveDate)
        self.ChoiceButtonMain.clicked.connect(MainWindow.FilePath)
        self.radioButtonshengkai1.clicked.connect(MainWindow.rbtnClicked)
        self.radioButtonshengkai2.clicked.connect(MainWindow.rbtnClicked)
        self.radioButtonshengkai3.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxguild.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxcompany.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxfire.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxemploy.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxshop.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxanyingdiantang.clicked.connect(MainWindow.rbtnClicked)

        self.checkBoxmonizhangongji.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxmonizhanfangyu.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxmonizhanfangkong.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxbugeizuozhan15.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxbugeizuozhan16.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxbugeizuozhan17.clicked.connect(MainWindow.rbtnClicked)

        self.checkBoxcollect1.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxcollect2.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxcollect3.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxcollect4.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxcollect5.clicked.connect(MainWindow.rbtnClicked)
        self.checkBoxcollect6.clicked.connect(MainWindow.rbtnClicked)

        self.checkBox.clicked.connect(MainWindow.rbtnClicked)
        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.ChoiceButtonMain.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9", None))
        self.SaveButtonMain.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.StartButtonMain.setText(QCoreApplication.translate("MainWindow", u"\u542f\u52a8", None))
        self.checkBoxguild.setText(QCoreApplication.translate("MainWindow", u"\u516c\u4f1a", None))
        self.checkBoxcompany.setText(QCoreApplication.translate("MainWindow", u"\u5bbf\u820d", None))
        self.checkBoxfire.setText(QCoreApplication.translate("MainWindow", u"\u89e3\u96c7", None))
        self.checkBoxemploy.setText(QCoreApplication.translate("MainWindow", u"\u96c7\u4f63", None))
        self.checkBoxshop.setText(QCoreApplication.translate("MainWindow", u"\u5546\u5e97", None))
        self.checkBoxanyingdiantang.setText(QCoreApplication.translate("MainWindow", u"\u6697\u5f71\u6bbf\u5802", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u5546\u5e97", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"RadioButton", None))
        self.radioButton_5.setText(QCoreApplication.translate("MainWindow", u"RadioButton", None))
        self.radioButton_6.setText(QCoreApplication.translate("MainWindow", u"RadioButton", None))
        self.groupBoxshengkai.setTitle(QCoreApplication.translate("MainWindow", u"\u5723\u51ef", None))
        self.radioButtonshengkai1.setText(QCoreApplication.translate("MainWindow", u"1\u6b21", None))
        self.radioButtonshengkai2.setText(QCoreApplication.translate("MainWindow", u"5\u6b21", None))
        self.radioButtonshengkai3.setText(QCoreApplication.translate("MainWindow", u"10\u6b21", None))
        self.groupBoxmonizhan.setTitle(QCoreApplication.translate("MainWindow", u"\u6a21\u62df\u6218", None))
        self.checkBoxmonizhangongji.setText(QCoreApplication.translate("MainWindow", u"\u653b\u51fb", None))
        self.checkBoxmonizhanfangyu.setText(QCoreApplication.translate("MainWindow", u"\u9632\u5fa1", None))
        self.checkBoxmonizhanfangkong.setText(QCoreApplication.translate("MainWindow", u"\u9632\u7a7a", None))
        self.groupBoxbugeizuozhan.setTitle(QCoreApplication.translate("MainWindow", u"\u8865\u7ed9\u4f5c\u6218", None))
        self.checkBoxbugeizuozhan15.setText(QCoreApplication.translate("MainWindow", u"1-5", None))
        self.checkBoxbugeizuozhan16.setText(QCoreApplication.translate("MainWindow", u"1-6", None))
        self.checkBoxbugeizuozhan17.setText(QCoreApplication.translate("MainWindow", u"1-7", None))
        self.groupBoxcollect.setTitle(QCoreApplication.translate("MainWindow", u"\u6536\u85cf", None))
        self.checkBoxcollect1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.checkBoxcollect2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.checkBoxcollect3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.checkBoxcollect4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.checkBoxcollect5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.checkBoxcollect6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\u63a2\u7d22", None))
    # retranslateUi

