# -*- coding: utf-8 -*-
from PyQt6.QtWidgets import QMainWindow
################################################################################
## Form generated from reading UI file 'win_CounterSideSetup.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGridLayout, QGroupBox,
    QHBoxLayout, QLineEdit, QPushButton, QRadioButton,
    QSizePolicy, QWidget)


class Ui_CSSetUp(QMainWindow):
    def setupUi(self, CSSetUp):
        if not CSSetUp.objectName():
            CSSetUp.setObjectName(u"CSSetUp")
        CSSetUp.resize(311, 797)
        self.gridLayoutWidget = QWidget(CSSetUp)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 10, 291, 151))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.checkBoxguild = QCheckBox(self.gridLayoutWidget)
        self.checkBoxguild.setObjectName(u"checkBoxguild")
        self.checkBoxguild.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxguild.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxguild, 0, 0, 1, 1)

        self.checkBoxcompany = QCheckBox(self.gridLayoutWidget)
        self.checkBoxcompany.setObjectName(u"checkBoxcompany")
        self.checkBoxcompany.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxcompany.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxcompany, 1, 0, 1, 1)

        self.checkBoxfire = QCheckBox(self.gridLayoutWidget)
        self.checkBoxfire.setObjectName(u"checkBoxfire")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxfire.sizePolicy().hasHeightForWidth())
        self.checkBoxfire.setSizePolicy(sizePolicy)
        self.checkBoxfire.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxfire.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxfire, 0, 1, 1, 1)

        self.checkBoxemploy = QCheckBox(self.gridLayoutWidget)
        self.checkBoxemploy.setObjectName(u"checkBoxemploy")
        self.checkBoxemploy.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxemploy.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxemploy, 1, 1, 1, 1)

        self.checkBoxanyingdiantang = QCheckBox(self.gridLayoutWidget)
        self.checkBoxanyingdiantang.setObjectName(u"checkBoxanyingdiantang")
        self.checkBoxanyingdiantang.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxanyingdiantang.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxanyingdiantang, 2, 0, 1, 1)

        self.checkBox = QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")

        self.gridLayout.addWidget(self.checkBox, 2, 1, 1, 1)

        self.groupBoxshengkai = QGroupBox(CSSetUp)
        self.groupBoxshengkai.setObjectName(u"groupBoxshengkai")
        self.groupBoxshengkai.setEnabled(True)
        self.groupBoxshengkai.setGeometry(QRect(0, 160, 130, 150))
        self.groupBoxshengkai.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.radioButtonshengkai0 = QRadioButton(self.groupBoxshengkai)
        self.radioButtonshengkai0.setObjectName(u"radioButtonshengkai0")
        self.radioButtonshengkai0.setGeometry(QRect(10, 25, 95, 20))
        self.radioButtonshengkai0.setChecked(True)
        self.radioButtonshengkai3 = QRadioButton(self.groupBoxshengkai)
        self.radioButtonshengkai3.setObjectName(u"radioButtonshengkai3")
        self.radioButtonshengkai3.setGeometry(QRect(10, 50, 95, 20))
        self.radioButtonshengkai6 = QRadioButton(self.groupBoxshengkai)
        self.radioButtonshengkai6.setObjectName(u"radioButtonshengkai6")
        self.radioButtonshengkai6.setGeometry(QRect(10, 75, 95, 20))
        self.radioButtonshengkai9 = QRadioButton(self.groupBoxshengkai)
        self.radioButtonshengkai9.setObjectName(u"radioButtonshengkai9")
        self.radioButtonshengkai9.setGeometry(QRect(10, 100, 95, 20))
        self.groupBox_2 = QGroupBox(CSSetUp)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QRect(160, 160, 130, 150))
        self.groupBox_2.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.radioButtonshopflash0 = QRadioButton(self.groupBox_2)
        self.radioButtonshopflash0.setObjectName(u"radioButtonshopflash0")
        self.radioButtonshopflash0.setGeometry(QRect(10, 30, 95, 20))
        self.radioButtonshopflash5 = QRadioButton(self.groupBox_2)
        self.radioButtonshopflash5.setObjectName(u"radioButtonshopflash5")
        self.radioButtonshopflash5.setGeometry(QRect(10, 65, 95, 20))
        self.checkBoxMW = QCheckBox(self.groupBox_2)
        self.checkBoxMW.setObjectName(u"checkBoxMW")
        self.checkBoxMW.setGeometry(QRect(10, 100, 80, 19))
        self.checkBoxMW.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.groupBoxmonizhan = QGroupBox(CSSetUp)
        self.groupBoxmonizhan.setObjectName(u"groupBoxmonizhan")
        self.groupBoxmonizhan.setGeometry(QRect(0, 320, 300, 90))
        self.groupBoxmonizhan.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxmonizhangongji = QCheckBox(self.groupBoxmonizhan)
        self.checkBoxmonizhangongji.setObjectName(u"checkBoxmonizhangongji")
        self.checkBoxmonizhangongji.setGeometry(QRect(0, 30, 80, 30))
        self.checkBoxmonizhangongji.setChecked(True)
        self.checkBoxmonizhanfangyu = QCheckBox(self.groupBoxmonizhan)
        self.checkBoxmonizhanfangyu.setObjectName(u"checkBoxmonizhanfangyu")
        self.checkBoxmonizhanfangyu.setGeometry(QRect(100, 30, 80, 30))
        self.checkBoxmonizhanfangyu.setChecked(True)
        self.checkBoxmonizhanfangkong = QCheckBox(self.groupBoxmonizhan)
        self.checkBoxmonizhanfangkong.setObjectName(u"checkBoxmonizhanfangkong")
        self.checkBoxmonizhanfangkong.setGeometry(QRect(200, 30, 80, 30))
        self.checkBoxmonizhanfangkong.setChecked(True)
        self.groupBoxbugeizuozhan = QGroupBox(CSSetUp)
        self.groupBoxbugeizuozhan.setObjectName(u"groupBoxbugeizuozhan")
        self.groupBoxbugeizuozhan.setGeometry(QRect(0, 400, 300, 90))
        self.groupBoxbugeizuozhan.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxbugeizuozhan15 = QCheckBox(self.groupBoxbugeizuozhan)
        self.checkBoxbugeizuozhan15.setObjectName(u"checkBoxbugeizuozhan15")
        self.checkBoxbugeizuozhan15.setGeometry(QRect(0, 30, 80, 30))
        self.checkBoxbugeizuozhan16 = QCheckBox(self.groupBoxbugeizuozhan)
        self.checkBoxbugeizuozhan16.setObjectName(u"checkBoxbugeizuozhan16")
        self.checkBoxbugeizuozhan16.setGeometry(QRect(70, 30, 80, 30))
        self.checkBoxbugeizuozhan16.setChecked(True)
        self.checkBoxbugeizuozhan17 = QCheckBox(self.groupBoxbugeizuozhan)
        self.checkBoxbugeizuozhan17.setObjectName(u"checkBoxbugeizuozhan17")
        self.checkBoxbugeizuozhan17.setGeometry(QRect(140, 30, 80, 30))
        self.checkBoxbugeizuozhan17.setChecked(True)
        self.checkBoxbugeizuozhan18 = QCheckBox(self.groupBoxbugeizuozhan)
        self.checkBoxbugeizuozhan18.setObjectName(u"checkBoxbugeizuozhan18")
        self.checkBoxbugeizuozhan18.setGeometry(QRect(210, 30, 80, 30))
        self.checkBoxbugeizuozhan18.setChecked(True)
        self.groupBoxcollect = QGroupBox(CSSetUp)
        self.groupBoxcollect.setObjectName(u"groupBoxcollect")
        self.groupBoxcollect.setGeometry(QRect(0, 480, 300, 130))
        self.groupBoxcollect.setStyleSheet(u"font: 700 9pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.checkBoxcollect1 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect1.setObjectName(u"checkBoxcollect1")
        self.checkBoxcollect1.setGeometry(QRect(0, 30, 80, 30))
        self.checkBoxcollect2 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect2.setObjectName(u"checkBoxcollect2")
        self.checkBoxcollect2.setGeometry(QRect(100, 30, 80, 30))
        self.checkBoxcollect2.setChecked(True)
        self.checkBoxcollect3 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect3.setObjectName(u"checkBoxcollect3")
        self.checkBoxcollect3.setGeometry(QRect(200, 30, 80, 30))
        self.checkBoxcollect3.setChecked(True)
        self.checkBoxcollect4 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect4.setObjectName(u"checkBoxcollect4")
        self.checkBoxcollect4.setGeometry(QRect(0, 70, 80, 30))
        self.checkBoxcollect5 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect5.setObjectName(u"checkBoxcollect5")
        self.checkBoxcollect5.setGeometry(QRect(100, 70, 80, 30))
        self.checkBoxcollect6 = QCheckBox(self.groupBoxcollect)
        self.checkBoxcollect6.setObjectName(u"checkBoxcollect6")
        self.checkBoxcollect6.setGeometry(QRect(200, 70, 80, 30))
        self.horizontalLayoutWidget = QWidget(CSSetUp)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(130, 740, 161, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ChoiceButtonMain = QPushButton(self.horizontalLayoutWidget)
        self.ChoiceButtonMain.setObjectName(u"ChoiceButtonMain")
        self.ChoiceButtonMain.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.ChoiceButtonMain.sizePolicy().hasHeightForWidth())
        self.ChoiceButtonMain.setSizePolicy(sizePolicy1)

        self.horizontalLayout.addWidget(self.ChoiceButtonMain)

        self.SaveButtonMain = QPushButton(self.horizontalLayoutWidget)
        self.SaveButtonMain.setObjectName(u"SaveButtonMain")
        self.SaveButtonMain.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.SaveButtonMain.sizePolicy().hasHeightForWidth())
        self.SaveButtonMain.setSizePolicy(sizePolicy1)

        self.horizontalLayout.addWidget(self.SaveButtonMain)

        self.lineEdit = QLineEdit(CSSetUp)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QRect(10, 750, 113, 21))

        self.retranslateUi(CSSetUp)

        QMetaObject.connectSlotsByName(CSSetUp)
    # setupUi

    def retranslateUi(self, CSSetUp):
        CSSetUp.setWindowTitle(QCoreApplication.translate("CSSetUp", u"CounterSide\u8bbe\u7f6e", None))
        self.checkBoxguild.setText(QCoreApplication.translate("CSSetUp", u"\u516c\u4f1a", None))
        self.checkBoxcompany.setText(QCoreApplication.translate("CSSetUp", u"\u5bbf\u820d", None))
        self.checkBoxfire.setText(QCoreApplication.translate("CSSetUp", u"\u89e3\u96c7", None))
        self.checkBoxemploy.setText(QCoreApplication.translate("CSSetUp", u"\u96c7\u4f63", None))
        self.checkBoxanyingdiantang.setText(QCoreApplication.translate("CSSetUp", u"\u6697\u5f71\u6bbf\u5802", None))
        self.checkBox.setText(QCoreApplication.translate("CSSetUp", u"\u63a2\u7d22", None))
        self.groupBoxshengkai.setTitle(QCoreApplication.translate("CSSetUp", u"\u5723\u51ef", None))
        self.radioButtonshengkai0.setText(QCoreApplication.translate("CSSetUp", u"0\u6b21", None))
        self.radioButtonshengkai3.setText(QCoreApplication.translate("CSSetUp", u"3\u6b21", None))
        self.radioButtonshengkai6.setText(QCoreApplication.translate("CSSetUp", u"6\u6b21", None))
        self.radioButtonshengkai9.setText(QCoreApplication.translate("CSSetUp", u"9\u6b21", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("CSSetUp", u"\u5546\u5e97", None))
        self.radioButtonshopflash0.setText(QCoreApplication.translate("CSSetUp", u"\u5237\u65b00\u6b21", None))
        self.radioButtonshopflash5.setText(QCoreApplication.translate("CSSetUp", u"\u5237\u65b05\u6b21", None))
        self.checkBoxMW.setText(QCoreApplication.translate("CSSetUp", u"\u5468\u6708\u5237\u65b0", None))
        self.groupBoxmonizhan.setTitle(QCoreApplication.translate("CSSetUp", u"\u6a21\u62df\u6218", None))
        self.checkBoxmonizhangongji.setText(QCoreApplication.translate("CSSetUp", u"\u653b\u51fb", None))
        self.checkBoxmonizhanfangyu.setText(QCoreApplication.translate("CSSetUp", u"\u9632\u5fa1", None))
        self.checkBoxmonizhanfangkong.setText(QCoreApplication.translate("CSSetUp", u"\u9632\u7a7a", None))
        self.groupBoxbugeizuozhan.setTitle(QCoreApplication.translate("CSSetUp", u"\u8865\u7ed9\u4f5c\u6218", None))
        self.checkBoxbugeizuozhan15.setText(QCoreApplication.translate("CSSetUp", u"1-5", None))
        self.checkBoxbugeizuozhan16.setText(QCoreApplication.translate("CSSetUp", u"1-6", None))
        self.checkBoxbugeizuozhan17.setText(QCoreApplication.translate("CSSetUp", u"1-7", None))
        self.checkBoxbugeizuozhan18.setText(QCoreApplication.translate("CSSetUp", u"1-8", None))
        self.groupBoxcollect.setTitle(QCoreApplication.translate("CSSetUp", u"\u6536\u85cf", None))
        self.checkBoxcollect1.setText(QCoreApplication.translate("CSSetUp", u"1", None))
        self.checkBoxcollect2.setText(QCoreApplication.translate("CSSetUp", u"2", None))
        self.checkBoxcollect3.setText(QCoreApplication.translate("CSSetUp", u"3", None))
        self.checkBoxcollect4.setText(QCoreApplication.translate("CSSetUp", u"4", None))
        self.checkBoxcollect5.setText(QCoreApplication.translate("CSSetUp", u"5", None))
        self.checkBoxcollect6.setText(QCoreApplication.translate("CSSetUp", u"6", None))
        self.ChoiceButtonMain.setText(QCoreApplication.translate("CSSetUp", u"\u9009\u62e9", None))
        self.SaveButtonMain.setText(QCoreApplication.translate("CSSetUp", u"\u4fdd\u5b58", None))
    # retranslateUi

